package com.katziio.collabwithkatz.entity.enums;

public enum Certificate {
    ASJA_CERTIFICATION,
    EFA_CERTIFICATION,
    POYNTER_ACES_CERTIFICATE,
    AMWA_CERTIFICATION,
    ASBPE_CERTIFICATION,
    ACA_PREMIERE_PRO_CERTIFICATION,
    FINAL_CUT_PRO_CERTIFICATION,
    CDE_CERTIFICATION,
    CVA_CERTIFICATION,
    OTHER_CERTIFICATION,

}
